coord_set_name : request_points_grid_05

satellite_search_params:
  satellite_name : landsat-8-c2-l2 #sentinel-2-l2a
  seasonal: False
  year: 2014 # only needed if seasonal = True
  search_start : "2013-04-01" #"2021-04-01" #"2015-11-01"
  search_end : "2014-03-31" #"2022-03-31" #"2016-10-31"
  stac_output : least_cloudy
  stac_api: planetary-compute # earth-search

model :
  num_features : 4000
  kernel_size : 3
  batch_size : 10
  device: cuda #cpu

dask :
    # n_per_run : 8 # deprecated
    chunksize : 500
    n_workers: 4
    threads_per_worker: 1
