satellite_image_params:
  satellite_name : sentinel-2-l2a #landsat-8-c2-l2
  search_start : "2021-04-01"
  search_end : "2022-03-31"
  stac_output : least_cloudy

num_features : 4000

dask :
  n_partitions : 250

