# See https://github.com/pangeo-data/cog-best-practices

GDAL_DISABLE_READDIR_ON_OPEN : EMPTY_DIR
GDAL_MAX_RAW_BLOCK_CACHE_SIZE : "200000000"
GDAL_SWATH_SIZE : "200000000"
VSI_CURL_CACHE_SIZE : "200000000"
AWS_REQUEST_PAYER : requester
