name: Unit Tests
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"

jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python libraries
        run: |
          pip install -r requirements.txt
          pip install -r requirements_test.txt

          # pip install git+https://${{secrets.GH_TOKEN_MACHINE_USER}}@github.com/IDinsight/mosaiks
          pip install .

      - name: Run Unit Tests
        env:
          PLANETARY_COMPUTE_TOKEN: ${{env.PLANETARY_COMPUTE_TOKEN}}
        run: |
          coverage run -m pytest tests
          coverage lcov

      - name: Coveralls Test Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
