name: Unit Tests
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"

jobs:
  ValidateModels:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.`0"

      - name: Install Python libraries
        run: |
          pip install -r requirements.txt
          pip install -r requirements_test.txt

          pip install git+https://${{env.GH_TOKEN_MACHINE_USER}}@github.com/IDinsight/mosaiks@external_run_prep

      - name: Run Unit Tests
        env:
          PLANETARY_COMPUTE_TOKEN: ${{env.PLANETARY_COMPUTE_TOKEN}}
        run: |
          coverage run -m pytest tests -m
          coverage lcov --include="src/mosaiks/*"

      - name: Coveralls Test Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
